version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=finalproject
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./laravel-backend/storage:/var/www/html/storage
      - ./laravel-backend/bootstrap/cache:/var/www/html/bootstrap/cache

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=finalproject
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
